[".config/ohmyzsh/.oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/ohmyzsh/.zsh_custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    exact = true
    refreshPeriod = "168h"
[".config/ohmyzsh/.zsh_custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    exact = true
    refreshPeriod = "168h"
[".config/ohmyzsh/.zsh_custom/plugins/zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions.git"
    exact = true
    refreshPeriod = "168h"
[".config/ohmyzsh/.zsh_custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    exact = true
    refreshPeriod = "168h"
[".config/fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    exact = true
["/.local/nvim-linux-x86_64"]
    type = "archive"
    url = "https://github.com/neovim/neovim/releases/download/v0.11.5/nvim-linux-x86_64.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
